id: A8F3DB209
title: 'Burgeoning Joy and Happiness: An Aspiration for the Welfare of the Great Hidden
  Land of Sikkim'
type: translation
pechas:
- I98AA0F9A
- I6F35FFBB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:00.486635
  last_modified_at: 2023-01-04 12:07:00.486645
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I98AA0F9A/C58E: 887C
  I6F35FFBB/A4B0: 887C
